title: Cours CIMAD N'Djaména 2025
logo: /assets/img/Gemini-generated-viruses-bacteria-2.jpeg
description: Notes du cours "Introduction à l'épidémiologie mathématique"
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
