title: Cours CIMAD 2025 N'Djaména (Introduction à l'épidémiologie mathématique)
logo: /assets/img/Gemini-generated-viruses-bacteria-2.jpeg
description: Mes notes de cours pour l'introduction à l'épidémiologie mathématique, CIMAD 2025 N'Djaména
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
